Refactored to fix PHP 7.4+
contributte/rabbitmq pull request #51
Opened 2021-06-07 21:36 UTC by bckp

2021-06-08 07:07 UTC, bckp commented
To discussion is, should we pass prev exception? I belive so, but so far it is not there...

2021-06-08 21:34 UTC, paveljanda requested changes
This way, we use `sprintf` for all string replacements 👍

2021-06-08 21:34 UTC, paveljanda commented on src/Console/Command/AbstractConsumerCommand.php
> +					"{$e->getMessage()}\n\n Available consumers: %s",
```suggestion
					"%s\n\n Available consumers: %s",
					$e->getMessage()
```

2021-06-11 05:12 UTC, bckp commented
fixed, @paveljanda

2021-06-11 09:05 UTC, paveljanda approved these changes

2021-06-11 09:05 UTC, merged

2021-06-11 09:05 UTC, paveljanda commented
Thanks